
tasks:
  - init: npm install && npm run build
    command: export HMR_HOST=`gp url 5173` && npm run dev

ports:
  - port: 5173
    onOpen: open-browser


vscode:
  extensions:
    - svelte.svelte-vscode git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

